ccflags-y += -Idrivers/media/platform/msm/camera/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera/cam_core

obj-$(CONFIG_SPECTRA_CAMERA) += cam_ois_dev.o cam_ois_core.o cam_ois_soc.o
obj-$(CONFIG_MACH_SDM845_JUDYPN) +=  lgit_onsemi/lgit_imx363_onsemi_ois.o
obj-$(CONFIG_MACH_SDM845_JUDYLN) +=  lgit_rohm/lgit_imx351_rohm_ois.o
obj-$(CONFIG_MACH_SDM845_JUDYP) +=  lgit_rohm/lgit_imx351_rohm_ois.o
obj-$(CONFIG_MACH_SDM845_STYLE3LM_DCM_JP) +=  lgit_onsemi/lgit_imx363_onsemi_ois.o
obj-$(CONFIG_MACH_SDM845_CAYMANSLM) +=  lgit_rohm/lgit_imx351_rohm_ois.o
