#ifndef _LGE_BACKLIGHT_DEF_H_
#define _LGE_BACKLIGHT_DEF_H_

#if IS_ENABLED(CONFIG_LGE_DISPLAY_USE_FSC)
#define DEFAULT_LGE_FSC_U3 20000
#define DEFAULT_LGE_FSC_U2 2500
#endif

#define DEFAULT_HBM_MODE 0x03;

char *lge_get_blmapname(enum lge_blmap_type type);

enum lge_blmap_type {
	LGE_BLMAP_DEFAULT = 0,
	LGE_BLMAP_PSM,
	LGE_BLMAP_GAL,
	LGE_BLMAP_BRI,
	LGE_BLMAP_HQC,
	LGE_BLMAP_MAX,
	LGE_BLMAP_DEFAULT_HL,
	LGE_BLMAP_PSM_HL,
	LGE_BLMAP_GAL_HL,
	LGE_BLMAP_BRI_HL,
	LGE_BLMAP_HQC_HL,
	LGE_BLMAP_MAX_HL,
	LGE_BLMAP_HBM_HD,
	LGE_BLMAP_VE,
	LGE_BLMAP_EX,
	LGE_BLMAP_HDR,
	LGE_BLMAP_TYPE_MAX
};
#endif // _LGE_BACKLIGHT_DEF_H_
