#ifndef _LGE_BACKLIGHT_DEF_H_
#define _LGE_BACKLIGHT_DEF_H_

#if IS_ENABLED(CONFIG_LGE_DISPLAY_USE_FSC)
#define DEFAULT_LGE_FSC_U3 20000
#define DEFAULT_LGE_FSC_U2 2500
#endif

#define DEFAULT_HBM_MODE 0x03;

#define FP_LHBM_OFF 0
#define FP_LHBM_ON 1
#define FP_LHBM_DEFAULT_BR_LVL	4095

char *lge_get_blmapname(enum lge_blmap_type type);

enum lge_blmap_type {
	LGE_BLMAP_DEFAULT = 0,
	LGE_BLMAP_PSM,
	LGE_BLMAP_GAL,
	LGE_BLMAP_BRI,
	LGE_BLMAP_HQC,
	LGE_BLMAP_MAX,
	LGE_BLMAP_DEFAULT_HL,
	LGE_BLMAP_PSM_HL,
	LGE_BLMAP_GAL_HL,
	LGE_BLMAP_BRI_HL,
	LGE_BLMAP_HQC_HL,
	LGE_BLMAP_MAX_HL,
	LGE_BLMAP_HBM_HD,
	LGE_BLMAP_VE,
	LGE_BLMAP_EX,
	LGE_BLMAP_HDR,
	LGE_BLMAP_VR,
	LGE_BLMAP_BR_ENHANCE,
	LGE_BLMAP_TYPE_MAX
};

enum fp_lhbm_state {
	LGE_FP_LHBM_OFF = 0,
	LGE_FP_LHBM_ON,
	LGE_FP_LHBM_READY,
	LGE_FP_LHBM_EXIT,
	LGE_FP_LHBM_SM_OFF = 10,
	LGE_FP_LHBM_SM_ON,
	LGE_FP_LHBM_FORCED_OFF = 20,
	LGE_FP_LHBM_FORCED_ON,
	LGE_FP_LHBM_FORCED_READY,
	LGE_FP_LHBM_FORCED_EXIT,
	LGE_FP_LHBM_STATE_MAX,
};
#endif // _LGE_BACKLIGHT_DEF_H_
