#
# Makefile for LGE USB Moisture Detector
#

ccflags-$(CONFIG_LGE_USB_LGMD18)		+= -DDEBUG
#ccflags-$(CONFIG_LGE_USB_LGMD18)		+= -DQUIET_MOISTURE_DETECTION

obj-$(CONFIG_LGE_USB_LGMD18)			+= lgmd18.o
obj-$(CONFIG_LGE_USB_LGMD18_JUDY)		+= lgmd18_judy.o
